export const fruitsList = ['Abiu', 'Açaí', 'Acerola', 'Akebi', 'Ackee', 'Apple', 'Apricot', 'Aratiles', 'Araza', 'Avocado', 'Banana', 'Bilberry', 'Blackberry', 'Blackcurrant', 'Blueberry', 'Boysenberry', 'Breadfruit', 'Canistel', 'Catmon', 'Cempedak', 'Cherimoya', 'Cherry', 'Citron', 'Cloudberry', 'Coconut', 'Cranberry', 'Currant', 'Damson', 'Date', 'Dragonfruit', 'Durian', 'Elderberry', 'Feijoa', 'Fig', 'Gac', 'Gooseberry', 'Grape', 'Raisin', 'Grapefruit', 'Guava', 'Honeyberry', 'Huckleberry', 'Jabuticaba', 'Jackfruit', 'Jambul', 'Jostaberry', 'Jujube', 'Kiwano', 'Kiwifruit', 'Kumquat', 'Lanzones', 'Lemon', 'Lime', 'Loganberry', 'Longan', 'Loquat', 'Lulo', 'Lychee', 'Macopa', 'Mango', 'Mangosteen', 'Marionberry', 'Medlar', 'Melon', 'Cantaloupe', 'Honeydew', 'Muskmelon', 'Watermelon', 'Mohsina', 'Mulberry', 'Nance', 'Nectarine', 'Orange', 'Clementine', 'Mandarine', 'Tangerine', 'Papaya', 'Passionfruit', 'Pawpaw', 'Peach', 'Pear', 'Persimmon', 'Pineapple', 'Pineberry', 'Plantain', 'Plum', 'Prune', 'Plumcot', 'Pomegranate', 'Pomelo', 'Quince', 'Raspberry', 'Salmonberry', 'Rambutan', 'Redcurrant', 'Salak', 'Santol', 'Sapodilla', 'Sapote', 'Sarguelas', 'Saskatoon', 'Satsuma', 'Sloe', 'Soursop', 'Strawberry', 'Tamarillo', 'Tamarind', 'Tangelo', 'Tayberry', 'Thimbleberry', 'Ximenia', 'Yuzu', 'Cucumber', 'Eggplant', 'Jalapeño', 'Olive', 'Pea', 'Pumpkin', 'Squash', 'Tomato', 'Zucchini'];
export const vegetablesList = ['artichoke', 'asparagus', 'broccoflower', 'broccoli', 'cabbage', 'kohlrabi', 'cauliflower', 'celery', 'chicory', 'cilantro', 'coriander', 'eggplant', 'endive', 'fiddleheads', 'frisee', 'fennel', 'greens', 'arugula', 'chard', 'kale', 'lettuce', 'spinach', 'beans', 'lentils', 'peanuts', 'peas', 'nettles', 'oca', 'okra', 'chives', 'garlic', 'leek', 'onion', 'shallot', 'pepper', 'jalapeño', 'habanero', 'paprika', 'radicchio', 'rhubarb', 'carrot', 'celeriac', 'corms', 'eddoe', 'konjac', 'taro', 'ginger', 'parsnip', 'radish', 'wasabi', 'horseradish', 'turnip', 'tubers', 'jicama', 'kumara', 'potato', 'yam', 'skirret', 'succotash', 'squashes', 'cucumber', 'delicata', 'tomatillo', 'tomato', 'topinambur', 'watercress'];
export const emotionsList = ['Anger', 'Annoyance', 'Contempt', 'Disgust', 'Irritation', 'Anxiety', 'Embarrassment', 'Fear', 'Helplessness', 'Powerlessness', 'Worry', 'Doubt', 'Envy', 'Frustration', 'Guilt', 'Shame', 'Boredom', 'Despair', 'Disappointment', 'Hurt', 'Sadness', 'Agitation', 'Stress', 'Shock', 'Tension', 'Amusement', 'Delight', 'Elation', 'Excitement', 'Happiness', 'Joy', 'Pleasure', 'Caring', 'Affection', 'Empathy', 'Friendliness', 'Love', 'Pride', 'Courage', 'Hope', 'Humility', 'Satisfaction', 'Trust', 'Calmness', 'Contentment', 'Relaxation', 'Relief', 'Serenity', 'Reactive', 'Interest', 'Politeness', 'Surprise'];
export const countriesList = ['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', "Côte d'Ivoire", 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Democratic Republic of the Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Holy See', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestine State', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States of America', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'];
export const animalsList = ["Albatross", "Alligator", "Alpaca", "Ant", "Antelope", "Ape", "Armadillo", "Ass", "Baboon", "Badger", "Bat", "Bear", "Beaver", "Bee", "Beetle", "Binturong", "Boar", "Bobcat", "Bull", "Butterfly", "Camel", "Cardinal", "Cat", "Cattle", "Cheetah", "Chicken", "Chimpanzee", "Chinchilla", "Chough", "Cobra", "Cockroach", "Cod", "Cormorant", "Cow", "Crab", "Crane", "Crocodile", "Crow", "Deer", "Dog", "Dogfish", "Dolphin", "Donkey", "Dove", "Duck", "Dunlin", "Eagle", "Echidna", "Eel", "Elephant", "Elk", "Emu", "Falcon", "Ferret", "Finch", "Flamingo", "Fly", "Fox", "Frog", "Gecko", "Gerbil", "Giant panda", "Giraffe", "Gnat", "Gnu", "Goat", "Goldfinch", "Goosander", "Goose", "Gorilla", "Goshawk", "Grasshopper", "Grouse", "Guanaco", "Guinea fowl", "Guinea pig", "Hamster", "Hare", "Hawk", "Hedgehog", "Heron", "Herring", "Hippopotamus", "Hornet", "Horse", "Human", "Hyena", "Jaguar", "Jay", "Jellyfish", "Junglefowl", "Kangaroo", "Kingbird", "Kinkajou", "Koala", "Ladybug", "Lapwing", "Lark", "Lemur", "Leopard", "Lion", "Lizard", "Llama", "Lobster", "Locust", "Lyrebird", "Mallard", "Meerkat", "Mole", "Mongoose", "Monkey", "Moose", "Mosquito", "Moth", "Mouse", "Narwhal", "Newt", "Nightingale", "Opossum", "Otter", "Ox", "Owl", "Oyster", "Panther", "Panda", "Partridge", "Peafowl", "Peccary", "Pelican", "Penguin", "Pheasant", "Pig", "Pigeon", "Platypus", "Polar bear", "Pony", "Porcupine", "Prairie dog", "Pug", "Quail", "Rabbit", "Raccoon", "Ram", "Rat", "Raven", "Rhinoceros", "Rook", "Salamander", "Salmon", "Sand dollar", "Sandpiper", "Sardine", "Seahorse", "Seal", "Sea otter", "Shark", "Sheep", "Skunk", "Snail", "Snake", "Spider", "Spoonbill", "Squid", "Squirrel", "Starfish", "Starling", "Stingray", "Swan", "Termite", "Thrush", "Tiger", "Toad", "Toucan", "Turkey", "Turtle", "Viper", "Wallaby", "Wasp", "Weasel", "Whale", "Wildebeest", "Wolf", "Wombat", "Zebra"];

export const colorsList = ['Aero', 'Alizarin', 'Almond', 'Amazon', 'Amber', 'Amethyst', 'Apricot', 
'Aqua', 'Aquamarine', 'Aureolin', 'Azure', 'Beaver', 'Beige', 'Bisque', 
'Bistre', 'Black', 'Blue', 'Blue-violet', 'Bluetiful', 'Blush', 'Bole', 
'Bone', 'Bronze', 'Brown', 'Buff', 'Burgundy', 'Burlywood', 'Byzantine', 
'Byzantium', 'Camel', 'Canary', 'Cardinal', 'Carmine', 'Carnelian', 'Catawba', 
'Celadon', 'Celeste', 'Cerise', 'Cerulean', 'Champagne', 'Charcoal', 'Chestnut', 
'Cinereous', 'Cinnabar', 'Citrine', 'Citron', 'Claret', 'Coffee', 'Copper', 'Coquelicot', 
'Coral', 'Cordovan', 'Corn', 'Cornsilk', 'Cream', 'Crimson', 'Cyan', 'Cyclamen', 'Dandelion',
 'Denim', 'Desert', 'Ebony', 'Ecru', 'Eggplant', 'Eggshell', 'Emerald', 'Eminence', 'Erin',
 'Fallow', 'Fandango', 'Fawn', 'Finn', 'Firebrick', 'Flame', 'Flax', 'Flirt', 'Frostbite', 
 'Fuchsia', 'Fulvous', 'Red',  'Green', 'Yellow', 'Orange', 'Pink', 'White',  'Gray', 'Grey', 
 'Purple', 'Indigo', 'Magenta', 'Lime', 'Navy', 'Olive', 'Maroon', 'Teal', 'Turquoise', 'Gold', 'Silver' ];